import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionWrapper from "./component/SessionWrapper"; // Import the SessionWrapper

import 'antd/dist/reset.css'; // Ant Design reset styles
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full"}>
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
